-- Table: public.contato

-- DROP TABLE public.contato;

CREATE TABLE public.contato
(
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
	nome character varying(50) NOT NULL COLLATE pg_catalog."default",
	email character varying(100) NOT NULL COLLATE pg_catalog."default",
	telefone character varying(13) NOT NULL COLLATE pg_catalog."default",
	id_pessoa bigint NOT NULL,
    CONSTRAINT tb_contato_pkey PRIMARY KEY (id),
	CONSTRAINT contato_idPessoa FOREIGN KEY (id_pessoa)
	REFERENCES public.pessoa (id) MATCH SIMPLE
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
    
)

TABLESPACE pg_default;

  INSERT INTO contato (nome, email, telefone, id_pessoa) values ('Robson', 'robson@robson.com', '61 99999-9999', 1);
